version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - "40001:40001"
    restart: unless-stopped
    environment:
      DELAY: 250
    logging:
      options:
        max-size: '1m'
        max-file: '10'
      driver: json-file
